# ===================================================================
# Spring Boot configuration for the "local" profile.
#
# This configuration overrides the application.yaml file.
#
#         TO BE USED FOR LOCAL DEVELOPMENTS
#
# ===================================================================
# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
  profiles:
    active: test

  devtools:
    restart:
      enabled: true
  jackson:
    serialization.indent_output: true

logging:
  level:
    eu.stelliant: DEBUG
    org.springframework.web.client: INFO
    com.darva: DEBUG

irsi:
  api:
    baseUrl: https://irsi.vabf.darva.com/domaines/ird/assureurs/{codeAssureur}/irsi/edi/v1
    username: 28953wssdgen
    password: 28953wssdgen
    debugging: false
